// <auto-generated />
using DnDSheetManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224013117_CriacaoDeNovasTabelasMagias")]
    partial class CriacaoDeNovasTabelasMagias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackBonus")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterResources");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterSpell", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CharacterId", "SpellId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ValueInGold")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Attack", b =>
                {
                    b.HasOne("DnDSheetManager.Domain.Entities.Character", "Character")
                        .WithMany("Attacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Character", b =>
                {
                    b.OwnsOne("DnDSheetManager.Domain.ValueObjects.AbilityScores", "Abilities", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<int>("Charisma")
                                .HasColumnType("int");

                            b1.Property<int>("Constitution")
                                .HasColumnType("int");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("int");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("int");

                            b1.Property<int>("Strength")
                                .HasColumnType("int");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("int");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DnDSheetManager.Domain.ValueObjects.Coins", "Wealth", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<int>("CopperPieces")
                                .HasColumnType("int");

                            b1.Property<int>("ElectrumPieces")
                                .HasColumnType("int");

                            b1.Property<int>("GoldPieces")
                                .HasColumnType("int");

                            b1.Property<int>("PlatinumPieces")
                                .HasColumnType("int");

                            b1.Property<int>("SilverPieces")
                                .HasColumnType("int");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DnDSheetManager.Domain.ValueObjects.Skills", "Skills", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<bool>("Acrobatics")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("AnimalHandling")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Arcana")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Athletics")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Deception")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("History")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Insight")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Intimidation")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Investigation")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Medicine")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Nature")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Perception")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Performance")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Persuasion")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Religion")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("SleightOfHand")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Stealth")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Survival")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Abilities")
                        .IsRequired();

                    b.Navigation("Skills")
                        .IsRequired();

                    b.Navigation("Wealth")
                        .IsRequired();
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("DnDSheetManager.Domain.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDSheetManager.Domain.Entities.Item", "Item")
                        .WithMany("CharacterItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterResource", b =>
                {
                    b.HasOne("DnDSheetManager.Domain.Entities.Character", "Character")
                        .WithMany("ClassResources")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.CharacterSpell", b =>
                {
                    b.HasOne("DnDSheetManager.Domain.Entities.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDSheetManager.Domain.Entities.Spell", "Spell")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Character", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("ClassResources");

                    b.Navigation("Inventory");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Item", b =>
                {
                    b.Navigation("CharacterItems");
                });

            modelBuilder.Entity("DnDSheetManager.Domain.Entities.Spell", b =>
                {
                    b.Navigation("CharacterSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
